apiVersion: v1
kind: PersistentVolume
metadata:
  name: flink-job-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/Docker/persistent
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-job-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: flink-job-pv
  storageClassName: standard