apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-kraft
  namespace: default
spec:
  serviceName: "kafka-service"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: confluentinc/cp-kafka:7.4.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_NODE_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-kraft-0.kafka-service.default.svc.cluster.local:9093"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,HOST://0.0.0.0:30092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092,HOST://localhost:30092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,HOST:PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CLUSTER_ID
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creator
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: topic-creator
          image: confluentinc/cp-kafka:7.4.0
          command:
            - /bin/bash
            - -c
            - |
              until kafka-topics --bootstrap-server kafka-service:9092 --list; do
                echo "Waiting for Kafka broker to be ready..."
                sleep 5
              done
              kafka-topics --create --bootstrap-server kafka-service:9092 --topic input-topic --partitions 3 --replication-factor 1
              kafka-topics --create --bootstrap-server kafka-service:9092 --topic output-topic --partitions 1 --replication-factor 1
      restartPolicy: Never